services:
  postgres:
    image: postgres:latest
    container_name: postgres

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: influxdb

    ports:
      - "8086:8086"

    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=
      - DOCKER_INFLUXDB_INIT_PASSWORD=
      - DOCKER_INFLUXDB_INIT_ORG=
      - DOCKER_INFLUXDB_INIT_BUCKET=

    restart: unless-stopped
