services:
  n8n:
    image: n8nio/n8n
    container_name: n8n

    ports:
      - "5678:5678"

    volumes:
      - ./n8n-data:/home/node/.n8n

    environment:
      - GENERIC_TIMEZONE: "Europe/Brussels"
      - TZ: "Europe/Brussels"

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=

    restart: unless-stopped
